runtime: nodejs10
handlers:
    # Serve all static files with urls ending with a file extension
    - url: /(.*\..+)$
      static_files: build/\1
      upload: build/(.*\..+)$
      secure: always
      # catch all handlers to index.html
    - url: /.*
      static_files: build/index.html
      upload: build/index.html
      secure: always