export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";

export const SIGNIN = "SIGNIN";
export const SIGNOUT = "SIGNOUT";
export const SIGNOUTALL = "SIGNOUTALL";
export const STORE_USERS = "STORE_USERS";
export const RESTORE_USERS = "RESTORE_USERS";

export const ADD_CALENDAR = "ADD_CALENDAR";
export const TOGGLE_CALENDAR = "TOGGLE_CALENDAR";
export const CLEAR_CALENDARS = "CLEAR_CALENDARS";
export const CLEAR_SPECIFIC_CALENDAR = "CLEAR_SPECIFIC_CALENDAR";
export const STORE_CALENDARS = "STORE_CALENDARS";
export const RESTORE_CALENDARS = "RESTORE_CALENDARS";

export const ADD_EVENT = "ADD_EVENT";
export const CLEAR_ALL_EVENTS = "CLEAR_ALL_EVENTS";
export const CLEAR_SPECIFIC_EVENTS = "CLEAR_SPECIFIC_EVENTS";
export const STORE_EVENTS = "STORE_EVENTS";
export const RESTORE_EVENTS = "RESTORE_EVENTS";

export const ADD_AVAILABILITY = "ADD_AVAILABILITY";
export const REMOVE_AVAILABILITY = "REMOVE_AVAILABILITY";
export const CLEAR_AVAILABILITIES = "CLEAR_AVAILABILITIES";
