export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";

export const SIGNIN = "SIGNIN";
export const SIGNOUT = "SIGNOUT";

export const ADD_CALENDAR = "ADD_CALENDAR";
export const TOGGLE_CALENDAR = "TOGGLE_CALENDAR";
export const CLEAR_CALENDARS = "CLEAR_CALENDARS";

export const ADD_EVENT = "ADD_EVENT";
export const CLEAR_ALL_EVENTS = "CLEAR_ALL_EVENTS";

export const ADD_AVAILABILITY = "ADD_AVAILABILITY";
export const REMOVE_AVAILABILITY = "REMOVE_AVAILABILITY";
export const CLEAR_AVAILABILITIES = "CLEAR_AVAILABILITIES";
